name: Sync Lyrics

on:
  schedule:
    - cron: '0 * * * *' # 每小时运行一次
  workflow_dispatch: {}

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout API repo
        uses: actions/checkout@v4
    
      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Get lyrics-db latest SHA
        id: lyrics_sha
        uses: actions/github-script@v7
        with:
          script: |
            const {data} = await github.rest.repos.getCommit({
              owner: 'Steve-XMH',
              repo: 'amll-ttml-db',
              ref: 'heads/main',
            });
            core.setOutput('sha', data.sha)

      - name: Restore lyrics cache
        id: cache_lyrics
        uses: actions/cache@v4
        with:
          path: lyrics-db
          key: lyrics-db-${{ steps.lyrics_sha.outputs.sha }}

      - name: Checkout lyrics database
        if: steps.cache_lyrics.outputs.cache-hit != 'true'
        uses: actions/checkout@v4
        with:
          repository: Steve-XMH/amll-ttml-db
          path: lyrics-db
          ref: ${{ steps.lyrics_sha.outputs.sha }}

      - name: Run sync script
        env:
          PRISMA_DATABASE_URL: ${{ secrets.PRISMA_DATABASE_URL }}
        run: pnpm exec tsx scripts/sync-lyrics.ts lyrics-db/ncm-lyrics 